### ISSUE TITLE
Should be deleted: MVAlinregbh has almost the same code

### ISSUE THREAD

**Issue by polarstern** [QuantLet/QID-1682-MVAlinreg2bh#2]

**Comment by lborke** [comment]
It is not so easy, because the 2 versions are used in the current version of the MVA book.

The only difference is obviusly only that:
Z = cbind(rep(1, length(xt[, 1])), xt[, 1], xt[, 2], xt[, 3], xt[, 4], xt[, 5], +xt[, 
    6], xt[, 7], xt[, 8], xt[, 9], xt[, 10], xt[, 11], xt[, 12], xt[, 13])

Z = cbind(rep(1, length(xt[, 1])), xt[, 4], xt[, 5], xt[, 6], xt[, 8], xt[, 9], xt[, 
    10], xt[, 11], xt[, 12], xt[, 13])

The rest is isomorphic ;-)))

**Comment by lborke** [comment]
But we should tag/denote such cases (where 2 or more Qs are "very similar") in a reasonable way, e.g. in the meta description, see-also field, or comments in the code.

**Comment by polarstern** [comment]
<<The only difference is obviusly only that:>>
Yes, that's why I created this issue.
In my MVA version only MVAlinregbh is used, so I thought it would be ok simply delete it.

**Comment by lborke** [comment]
However, I have updated the description of this Gitlet ;-)
[vali-S, should be deleted - see issue, very "similar" to QID-1615-MVAlinregbh]
